<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Your email address_uploader_email</name>
   <tag></tag>
   <elementGuidId>11485fd6-48cb-4daf-9c47-b5c51e36e74a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uploader_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uploader_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a99601f-eea3-4647-87d7-86d2b390e7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uploader_email</value>
      <webElementGuid>e4972853-0308-43fe-9624-231e857e71df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c9b969d5-358e-4032-adcb-65552e29f7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span12</value>
      <webElementGuid>a9f2d78c-44d2-4b47-a364-7d56066a75fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uploader_email</value>
      <webElementGuid>a06c5091-d19c-4318-9a7c-a6a199269288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uploader_email&quot;)</value>
      <webElementGuid>bb3ab7c0-37c0-4920-8c41-729b9179b94d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uploader_email']</value>
      <webElementGuid>b1b762cb-424c-4ea0-9bf2-cb930dcfc55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form']/div/div/div[2]/input</value>
      <webElementGuid>1abfba1c-6115-4dc5-b0fa-5998acc24dd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>8e8957c6-e8ed-4c35-9106-27bbf24978e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'uploader_email' and @type = 'text' and @id = 'uploader_email']</value>
      <webElementGuid>5d2f9e9b-e313-4056-ae08-bfcd2a28ed30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
